server:
  port: 8080

management:
  security:
    enabled: true

security:
  user:
    name: user
    password: pwd123

spring:
  boot:
    admin:
      url: http://localhost:8080
      auth:
        username: user
        password: 123
      client:
        metadata:
          user:
            name: user
            password: 123
  application:
    name: admin-server

logging:
  level:
    org.springframework.security: INFO

zuul.sensitiveHeaders:
